name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: {{description}}
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.2.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9
  mockito: ^5.4.4
  go_router_builder: ^2.4.1
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

scripts:
  gen: dart run build_runner watch --delete-conflicting-outputs
  lint: flutter analyze
